rootProject.name = "vitamin-compose"
include(":foundation")
include(":buttons")
include(":text-inputs")
include(":switches")
include(":appbars")
include(":radiobuttons")
include(":progressbars")
include(":checkboxes")
include(":ratings")
include(":modals")
include(":sample")
include(":dividers")
include(":tabs")
include(":tags")
include(":prices")
include(":menus")
