rootProject.name = "vitamin-compose"
include(":foundation")
include(":buttons")
include(":text-inputs")
include(":switches")
include(":appbars")
include(":radiobuttons")
include(":progressbar")
include(":checkboxes")
include(":sample")
