package com.decathlon.vitamin.compose.vitaminassets

import androidx.compose.ui.graphics.vector.ImageVector
import com.decathlon.vitamin.compose.VitaminAssets
import com.decathlon.vitamin.compose.vitaminassets.flags.Ad
import com.decathlon.vitamin.compose.vitaminassets.flags.Ae
import com.decathlon.vitamin.compose.vitaminassets.flags.Af
import com.decathlon.vitamin.compose.vitaminassets.flags.Ag
import com.decathlon.vitamin.compose.vitaminassets.flags.Ai
import com.decathlon.vitamin.compose.vitaminassets.flags.Al
import com.decathlon.vitamin.compose.vitaminassets.flags.Am
import com.decathlon.vitamin.compose.vitaminassets.flags.An
import com.decathlon.vitamin.compose.vitaminassets.flags.Ao
import com.decathlon.vitamin.compose.vitaminassets.flags.Ar
import com.decathlon.vitamin.compose.vitaminassets.flags.As
import com.decathlon.vitamin.compose.vitaminassets.flags.At
import com.decathlon.vitamin.compose.vitaminassets.flags.Au
import com.decathlon.vitamin.compose.vitaminassets.flags.Aw
import com.decathlon.vitamin.compose.vitaminassets.flags.Ax
import com.decathlon.vitamin.compose.vitaminassets.flags.Az
import com.decathlon.vitamin.compose.vitaminassets.flags.Ba
import com.decathlon.vitamin.compose.vitaminassets.flags.Bb
import com.decathlon.vitamin.compose.vitaminassets.flags.Bd
import com.decathlon.vitamin.compose.vitaminassets.flags.Be
import com.decathlon.vitamin.compose.vitaminassets.flags.Bf
import com.decathlon.vitamin.compose.vitaminassets.flags.Bg
import com.decathlon.vitamin.compose.vitaminassets.flags.Bh
import com.decathlon.vitamin.compose.vitaminassets.flags.Bi
import com.decathlon.vitamin.compose.vitaminassets.flags.Bj
import com.decathlon.vitamin.compose.vitaminassets.flags.Bl
import com.decathlon.vitamin.compose.vitaminassets.flags.Bm
import com.decathlon.vitamin.compose.vitaminassets.flags.Bn
import com.decathlon.vitamin.compose.vitaminassets.flags.Bo
import com.decathlon.vitamin.compose.vitaminassets.flags.Br
import com.decathlon.vitamin.compose.vitaminassets.flags.Bs
import com.decathlon.vitamin.compose.vitaminassets.flags.Bt
import com.decathlon.vitamin.compose.vitaminassets.flags.Bv
import com.decathlon.vitamin.compose.vitaminassets.flags.Bw
import com.decathlon.vitamin.compose.vitaminassets.flags.By
import com.decathlon.vitamin.compose.vitaminassets.flags.Bz
import com.decathlon.vitamin.compose.vitaminassets.flags.Ca
import com.decathlon.vitamin.compose.vitaminassets.flags.Caf
import com.decathlon.vitamin.compose.vitaminassets.flags.Cas
import com.decathlon.vitamin.compose.vitaminassets.flags.Cc
import com.decathlon.vitamin.compose.vitaminassets.flags.Cd
import com.decathlon.vitamin.compose.vitaminassets.flags.Ceu
import com.decathlon.vitamin.compose.vitaminassets.flags.Cf
import com.decathlon.vitamin.compose.vitaminassets.flags.Cg
import com.decathlon.vitamin.compose.vitaminassets.flags.Ch
import com.decathlon.vitamin.compose.vitaminassets.flags.Ci
import com.decathlon.vitamin.compose.vitaminassets.flags.Ck
import com.decathlon.vitamin.compose.vitaminassets.flags.Cl
import com.decathlon.vitamin.compose.vitaminassets.flags.Cm
import com.decathlon.vitamin.compose.vitaminassets.flags.Cn
import com.decathlon.vitamin.compose.vitaminassets.flags.Cna
import com.decathlon.vitamin.compose.vitaminassets.flags.Co
import com.decathlon.vitamin.compose.vitaminassets.flags.Coc
import com.decathlon.vitamin.compose.vitaminassets.flags.Cr
import com.decathlon.vitamin.compose.vitaminassets.flags.Csa
import com.decathlon.vitamin.compose.vitaminassets.flags.Cu
import com.decathlon.vitamin.compose.vitaminassets.flags.Cv
import com.decathlon.vitamin.compose.vitaminassets.flags.Cw
import com.decathlon.vitamin.compose.vitaminassets.flags.Cx
import com.decathlon.vitamin.compose.vitaminassets.flags.Cy
import com.decathlon.vitamin.compose.vitaminassets.flags.Cz
import com.decathlon.vitamin.compose.vitaminassets.flags.De
import com.decathlon.vitamin.compose.vitaminassets.flags.Dj
import com.decathlon.vitamin.compose.vitaminassets.flags.Dk
import com.decathlon.vitamin.compose.vitaminassets.flags.Dm
import com.decathlon.vitamin.compose.vitaminassets.flags.Do
import com.decathlon.vitamin.compose.vitaminassets.flags.Dz
import com.decathlon.vitamin.compose.vitaminassets.flags.Ec
import com.decathlon.vitamin.compose.vitaminassets.flags.Ee
import com.decathlon.vitamin.compose.vitaminassets.flags.Eg
import com.decathlon.vitamin.compose.vitaminassets.flags.Eh
import com.decathlon.vitamin.compose.vitaminassets.flags.Er
import com.decathlon.vitamin.compose.vitaminassets.flags.Es
import com.decathlon.vitamin.compose.vitaminassets.flags.Et
import com.decathlon.vitamin.compose.vitaminassets.flags.Eu
import com.decathlon.vitamin.compose.vitaminassets.flags.Fi
import com.decathlon.vitamin.compose.vitaminassets.flags.Fj
import com.decathlon.vitamin.compose.vitaminassets.flags.Fk
import com.decathlon.vitamin.compose.vitaminassets.flags.Fm
import com.decathlon.vitamin.compose.vitaminassets.flags.Fo
import com.decathlon.vitamin.compose.vitaminassets.flags.Fr
import com.decathlon.vitamin.compose.vitaminassets.flags.Ga
import com.decathlon.vitamin.compose.vitaminassets.flags.Gb
import com.decathlon.vitamin.compose.vitaminassets.flags.GbEng
import com.decathlon.vitamin.compose.vitaminassets.flags.GbNir
import com.decathlon.vitamin.compose.vitaminassets.flags.GbSct
import com.decathlon.vitamin.compose.vitaminassets.flags.GbWls
import com.decathlon.vitamin.compose.vitaminassets.flags.GbZet
import com.decathlon.vitamin.compose.vitaminassets.flags.Gd
import com.decathlon.vitamin.compose.vitaminassets.flags.Ge
import com.decathlon.vitamin.compose.vitaminassets.flags.Gf
import com.decathlon.vitamin.compose.vitaminassets.flags.Gg
import com.decathlon.vitamin.compose.vitaminassets.flags.Gh
import com.decathlon.vitamin.compose.vitaminassets.flags.Gi
import com.decathlon.vitamin.compose.vitaminassets.flags.Gl
import com.decathlon.vitamin.compose.vitaminassets.flags.Gm
import com.decathlon.vitamin.compose.vitaminassets.flags.Gn
import com.decathlon.vitamin.compose.vitaminassets.flags.Gp
import com.decathlon.vitamin.compose.vitaminassets.flags.Gq
import com.decathlon.vitamin.compose.vitaminassets.flags.Gr
import com.decathlon.vitamin.compose.vitaminassets.flags.Gs
import com.decathlon.vitamin.compose.vitaminassets.flags.Gt
import com.decathlon.vitamin.compose.vitaminassets.flags.Gu
import com.decathlon.vitamin.compose.vitaminassets.flags.Gw
import com.decathlon.vitamin.compose.vitaminassets.flags.Gy
import com.decathlon.vitamin.compose.vitaminassets.flags.Hk
import com.decathlon.vitamin.compose.vitaminassets.flags.Hm
import com.decathlon.vitamin.compose.vitaminassets.flags.Hn
import com.decathlon.vitamin.compose.vitaminassets.flags.Hr
import com.decathlon.vitamin.compose.vitaminassets.flags.Ht
import com.decathlon.vitamin.compose.vitaminassets.flags.Hu
import com.decathlon.vitamin.compose.vitaminassets.flags.Id
import com.decathlon.vitamin.compose.vitaminassets.flags.Ie
import com.decathlon.vitamin.compose.vitaminassets.flags.Il
import com.decathlon.vitamin.compose.vitaminassets.flags.Im
import com.decathlon.vitamin.compose.vitaminassets.flags.In
import com.decathlon.vitamin.compose.vitaminassets.flags.Io
import com.decathlon.vitamin.compose.vitaminassets.flags.Iq
import com.decathlon.vitamin.compose.vitaminassets.flags.Ir
import com.decathlon.vitamin.compose.vitaminassets.flags.Is
import com.decathlon.vitamin.compose.vitaminassets.flags.It
import com.decathlon.vitamin.compose.vitaminassets.flags.Je
import com.decathlon.vitamin.compose.vitaminassets.flags.Jm
import com.decathlon.vitamin.compose.vitaminassets.flags.Jo
import com.decathlon.vitamin.compose.vitaminassets.flags.Jp
import com.decathlon.vitamin.compose.vitaminassets.flags.Ke
import com.decathlon.vitamin.compose.vitaminassets.flags.Kg
import com.decathlon.vitamin.compose.vitaminassets.flags.Kh
import com.decathlon.vitamin.compose.vitaminassets.flags.Ki
import com.decathlon.vitamin.compose.vitaminassets.flags.Km
import com.decathlon.vitamin.compose.vitaminassets.flags.Kn
import com.decathlon.vitamin.compose.vitaminassets.flags.Kp
import com.decathlon.vitamin.compose.vitaminassets.flags.Kr
import com.decathlon.vitamin.compose.vitaminassets.flags.Kw
import com.decathlon.vitamin.compose.vitaminassets.flags.Ky
import com.decathlon.vitamin.compose.vitaminassets.flags.Kz
import com.decathlon.vitamin.compose.vitaminassets.flags.La
import com.decathlon.vitamin.compose.vitaminassets.flags.Lb
import com.decathlon.vitamin.compose.vitaminassets.flags.Lc
import com.decathlon.vitamin.compose.vitaminassets.flags.Lgbt
import com.decathlon.vitamin.compose.vitaminassets.flags.Li
import com.decathlon.vitamin.compose.vitaminassets.flags.Lk
import com.decathlon.vitamin.compose.vitaminassets.flags.Lr
import com.decathlon.vitamin.compose.vitaminassets.flags.Ls
import com.decathlon.vitamin.compose.vitaminassets.flags.Lt
import com.decathlon.vitamin.compose.vitaminassets.flags.Lu
import com.decathlon.vitamin.compose.vitaminassets.flags.Lv
import com.decathlon.vitamin.compose.vitaminassets.flags.Ly
import com.decathlon.vitamin.compose.vitaminassets.flags.Ma
import com.decathlon.vitamin.compose.vitaminassets.flags.Mc
import com.decathlon.vitamin.compose.vitaminassets.flags.Md
import com.decathlon.vitamin.compose.vitaminassets.flags.Me
import com.decathlon.vitamin.compose.vitaminassets.flags.Mf
import com.decathlon.vitamin.compose.vitaminassets.flags.Mg
import com.decathlon.vitamin.compose.vitaminassets.flags.Mh
import com.decathlon.vitamin.compose.vitaminassets.flags.Mk
import com.decathlon.vitamin.compose.vitaminassets.flags.Ml
import com.decathlon.vitamin.compose.vitaminassets.flags.Mm
import com.decathlon.vitamin.compose.vitaminassets.flags.Mn
import com.decathlon.vitamin.compose.vitaminassets.flags.Mo
import com.decathlon.vitamin.compose.vitaminassets.flags.Mp
import com.decathlon.vitamin.compose.vitaminassets.flags.Mq
import com.decathlon.vitamin.compose.vitaminassets.flags.Mr
import com.decathlon.vitamin.compose.vitaminassets.flags.Ms
import com.decathlon.vitamin.compose.vitaminassets.flags.Mt
import com.decathlon.vitamin.compose.vitaminassets.flags.Mu
import com.decathlon.vitamin.compose.vitaminassets.flags.Mv
import com.decathlon.vitamin.compose.vitaminassets.flags.Mw
import com.decathlon.vitamin.compose.vitaminassets.flags.Mx
import com.decathlon.vitamin.compose.vitaminassets.flags.My
import com.decathlon.vitamin.compose.vitaminassets.flags.Mz
import com.decathlon.vitamin.compose.vitaminassets.flags.Na
import com.decathlon.vitamin.compose.vitaminassets.flags.Nc
import com.decathlon.vitamin.compose.vitaminassets.flags.Ne
import com.decathlon.vitamin.compose.vitaminassets.flags.Nf
import com.decathlon.vitamin.compose.vitaminassets.flags.Ng
import com.decathlon.vitamin.compose.vitaminassets.flags.Ni
import com.decathlon.vitamin.compose.vitaminassets.flags.Nl
import com.decathlon.vitamin.compose.vitaminassets.flags.No
import com.decathlon.vitamin.compose.vitaminassets.flags.Np
import com.decathlon.vitamin.compose.vitaminassets.flags.Nr
import com.decathlon.vitamin.compose.vitaminassets.flags.Nu
import com.decathlon.vitamin.compose.vitaminassets.flags.Nz
import com.decathlon.vitamin.compose.vitaminassets.flags.Om
import com.decathlon.vitamin.compose.vitaminassets.flags.Pa
import com.decathlon.vitamin.compose.vitaminassets.flags.Pe
import com.decathlon.vitamin.compose.vitaminassets.flags.Pf
import com.decathlon.vitamin.compose.vitaminassets.flags.Pg
import com.decathlon.vitamin.compose.vitaminassets.flags.Ph
import com.decathlon.vitamin.compose.vitaminassets.flags.Pk
import com.decathlon.vitamin.compose.vitaminassets.flags.Pl
import com.decathlon.vitamin.compose.vitaminassets.flags.Pm
import com.decathlon.vitamin.compose.vitaminassets.flags.Pn
import com.decathlon.vitamin.compose.vitaminassets.flags.Pr
import com.decathlon.vitamin.compose.vitaminassets.flags.Ps
import com.decathlon.vitamin.compose.vitaminassets.flags.Pt
import com.decathlon.vitamin.compose.vitaminassets.flags.Pw
import com.decathlon.vitamin.compose.vitaminassets.flags.Py
import com.decathlon.vitamin.compose.vitaminassets.flags.Qa
import com.decathlon.vitamin.compose.vitaminassets.flags.Re
import com.decathlon.vitamin.compose.vitaminassets.flags.Ro
import com.decathlon.vitamin.compose.vitaminassets.flags.Rs
import com.decathlon.vitamin.compose.vitaminassets.flags.Ru
import com.decathlon.vitamin.compose.vitaminassets.flags.Rw
import com.decathlon.vitamin.compose.vitaminassets.flags.Sa
import com.decathlon.vitamin.compose.vitaminassets.flags.Sb
import com.decathlon.vitamin.compose.vitaminassets.flags.Sc
import com.decathlon.vitamin.compose.vitaminassets.flags.Sd
import com.decathlon.vitamin.compose.vitaminassets.flags.Se
import com.decathlon.vitamin.compose.vitaminassets.flags.Sg
import com.decathlon.vitamin.compose.vitaminassets.flags.Sh
import com.decathlon.vitamin.compose.vitaminassets.flags.Si
import com.decathlon.vitamin.compose.vitaminassets.flags.Sj
import com.decathlon.vitamin.compose.vitaminassets.flags.Sk
import com.decathlon.vitamin.compose.vitaminassets.flags.Sl
import com.decathlon.vitamin.compose.vitaminassets.flags.Sm
import com.decathlon.vitamin.compose.vitaminassets.flags.Sn
import com.decathlon.vitamin.compose.vitaminassets.flags.So
import com.decathlon.vitamin.compose.vitaminassets.flags.Sr
import com.decathlon.vitamin.compose.vitaminassets.flags.Ss
import com.decathlon.vitamin.compose.vitaminassets.flags.St
import com.decathlon.vitamin.compose.vitaminassets.flags.Sv
import com.decathlon.vitamin.compose.vitaminassets.flags.Sx
import com.decathlon.vitamin.compose.vitaminassets.flags.Sy
import com.decathlon.vitamin.compose.vitaminassets.flags.Sz
import com.decathlon.vitamin.compose.vitaminassets.flags.Tc
import com.decathlon.vitamin.compose.vitaminassets.flags.Td
import com.decathlon.vitamin.compose.vitaminassets.flags.Tg
import com.decathlon.vitamin.compose.vitaminassets.flags.Th
import com.decathlon.vitamin.compose.vitaminassets.flags.Tj
import com.decathlon.vitamin.compose.vitaminassets.flags.Tk
import com.decathlon.vitamin.compose.vitaminassets.flags.Tl
import com.decathlon.vitamin.compose.vitaminassets.flags.Tm
import com.decathlon.vitamin.compose.vitaminassets.flags.Tn
import com.decathlon.vitamin.compose.vitaminassets.flags.To
import com.decathlon.vitamin.compose.vitaminassets.flags.Tr
import com.decathlon.vitamin.compose.vitaminassets.flags.Tt
import com.decathlon.vitamin.compose.vitaminassets.flags.Tv
import com.decathlon.vitamin.compose.vitaminassets.flags.Tw
import com.decathlon.vitamin.compose.vitaminassets.flags.Tz
import com.decathlon.vitamin.compose.vitaminassets.flags.Ua
import com.decathlon.vitamin.compose.vitaminassets.flags.Ug
import com.decathlon.vitamin.compose.vitaminassets.flags.Um
import com.decathlon.vitamin.compose.vitaminassets.flags.Us
import com.decathlon.vitamin.compose.vitaminassets.flags.UsCa
import com.decathlon.vitamin.compose.vitaminassets.flags.Uy
import com.decathlon.vitamin.compose.vitaminassets.flags.Uz
import com.decathlon.vitamin.compose.vitaminassets.flags.Va
import com.decathlon.vitamin.compose.vitaminassets.flags.Vc
import com.decathlon.vitamin.compose.vitaminassets.flags.Ve
import com.decathlon.vitamin.compose.vitaminassets.flags.Vg
import com.decathlon.vitamin.compose.vitaminassets.flags.Vi
import com.decathlon.vitamin.compose.vitaminassets.flags.Vn
import com.decathlon.vitamin.compose.vitaminassets.flags.Vu
import com.decathlon.vitamin.compose.vitaminassets.flags.Wf
import com.decathlon.vitamin.compose.vitaminassets.flags.Ws
import com.decathlon.vitamin.compose.vitaminassets.flags.Ww
import com.decathlon.vitamin.compose.vitaminassets.flags.Xk
import com.decathlon.vitamin.compose.vitaminassets.flags.Ye
import com.decathlon.vitamin.compose.vitaminassets.flags.Yt
import com.decathlon.vitamin.compose.vitaminassets.flags.Za
import com.decathlon.vitamin.compose.vitaminassets.flags.Zm
import com.decathlon.vitamin.compose.vitaminassets.flags.Zw
import kotlin.collections.List as ____KtList

public object FlagsGroup

public val VitaminAssets.Flags: FlagsGroup
  get() = FlagsGroup

private var __AllAssets: ____KtList<ImageVector>? = null

public val FlagsGroup.AllAssets: ____KtList<ImageVector>
  get() {
    if (__AllAssets != null) {
      return __AllAssets!!
    }
    __AllAssets= listOf(Ga, Gh, Mh, Zw, Tg, De, Gm, Mm, In, At, Vg, Sr, Cx, Gw, Bd, Af, Mp, Iq, Rs,
        Kg, Ir, Lr, My, Pf, Lc, GbSct, Tn, Ww, Ch, Ck, Bn, Sv, Tl, Pr, Sm, Hn, Hu, Cy, Pk, Bw, Sl,
        Ad, Tt, Nu, Az, Be, Cn, Py, Jp, Ec, Mr, Pe, Bz, Ml, Sn, Is, Cw, Et, Gd, Sy, Pw, Gb, Ai, Nr,
        Nl, Lk, Um, Fi, Nz, Sh, Tv, Kw, Sj, Tj, Vi, Tr, Ke, Bs, Km, Fr, Ls, Ceu, Vc, Mk, Yt, Ge, Ws,
        Hr, Pm, Dm, Id, Zm, Nf, Cu, Il, Uy, Im, Vn, Ms, Ss, Bh, Ly, Gs, Ma, Am, Si, Jm, Ao, Bf, Fj,
        Vu, Lb, Cg, Me, Gf, Ye, Gg, Mq, Tz, Gp, Coc, Do, Mx, Lgbt, Fk, Fm, Gt, Ht, Kn, Pl, Bg, Gu,
        Sc, Wf, La, Fo, Sa, Us, Lv, Td, Csa, Io, Lu, GbZet, Mw, Caf, Tk, Sd, Mg, UsCa, Pa, Za, Cv,
        As, Sg, It, Qa, Cas, Cd, Ky, Bj, Bi, Xk, Br, Ie, Gi, Hk, Pg, St, Hm, By, Cl, Re, Tc, Na, Sb,
        Mz, Mn, Rw, So, Np, Mu, Lt, Cm, Ae, Eg, Kp, Gr, Mt, Ca, Ee, Aw, Ci, Ps, Th, An, Cna, Kr, Ro,
        Cz, Uz, Gq, Ug, Eh, Li, Ve, Sk, Va, Ua, Ph, GbWls, Dk, Au, GbNir, Dz, Ki, Je, Es, Md, Bl,
        Bb, Nc, Bm, Se, Ar, Mo, Gy, Tw, Kh, Bo, Al, Pn, Dj, Ng, Mf, Om, Jo, Gl, Bt, Ba, Gn, Ni, Ne,
        Ag, Mc, Er, Sz, Sx, Cc, Kz, Mv, To, Cf, Ru, Cr, Eu, Pt, Bv, Ax, Co, GbEng, Tm, No)
    return __AllAssets!!
  }
